constellation/urls.py
import importlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('admin/doc/', include('django.contrib.admindocs.urls'), name='admindocs'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
]

# Load urls from other apps if they are loaded
for app in settings.INSTALLED_APPS:
    if app.startswith("django"):
        continue
    try:
        urlpatterns.append(path(f'{app}/', include(app + '.urls')))
    except ModuleNotFoundError:
        pass


# If Django Rest Framework is installed, then add a REST API
try:
    from rest_framework import routers
except ImportError:
    pass
else:
    router = routers.DefaultRouter()

    for app in settings.LOCAL_APPS:
        try:
            api_urls = importlib.import_module(f'{app}.api.urls')
            # noinspection PyUnresolvedReferences
            api_urls.register_routes(router)
        except ModuleNotFoundError:
            pass

    if 'dnsmanager' in settings.INSTALLED_APPS:
        from dnsmanager.api.views import RecordViewSet, ZoneViewSet
        router.register('dnsmanager/record', RecordViewSet)
        router.register('dnsmanager/zone', ZoneViewSet)

    urlpatterns += [
        url(r'^api/', include(router.urls)),
    ]

debug/urls.py
from django.urls import path

from . import views


app_name = 'debug'
urlpatterns = [
    path('graph/', views.GraphModelsView.as_view(), name='graph_models'),
]

member/urls.py
from django.contrib import admin
from django.contrib.admin.views.autocomplete import AutocompleteJsonView
from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path("signup/", views.SignupView.as_view(), name='signup'),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name='user_detail'),
    path("update/<int:pk>/", views.UserUpdateView.as_view(), name='user_update'),
    path('validate_email/resend/<int:pk>/', views.UserResendValidationEmailView.as_view(),
         name='email_validation_resend'),
    path('validate_email/<uidb64>/<token>/', views.UserValidateView.as_view(), name='email_validation'),
    path("impersonate/<int:pk>/", views.UserImpersonateView.as_view(), name="user_impersonate"),
    path("reset-impersonate/", views.ResetAdminView.as_view(), name="reset_impersonate"),
    # Autocomplete view that don't require to be staff
    path("autocomplete/", AutocompleteJsonView.as_view(admin_site=admin.site), name="autocomplete"),
]

constellation/templates/base.html
{% load i18n static apps %}

{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}

<!DOCTYPE html>
<html class="h-100" lang="{{ LANGUAGE_CODE|default:'en' }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Constellation</title>
    <meta name="description" content="Constellation (indev)">

    {# Import bootstrap files #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>

    {# Load custom stylesheet #}
    <link rel="stylesheet" href="{% static 'constellation/css/custom.css' %}">

    {% block form_media %}
        {# Add eventual dependencies for the widgets of a form #}
        {{ form.media }}
    {% endblock %}

    {% block extracss %}{% endblock %}
</head>

<body class="d-flex w-100 h-100 flex-column">
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary fixed-navbar shadow-sm">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Constellation</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-person"></i>
                        <span>{{ user }}</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right"
                         aria-labelledby="navbarDropdownMenuLink">

                        <a class="dropdown-item" href="{% url 'member:user_detail' pk=user.pk %}"><i class="bi bi-person"></i> {% trans "My account" %}</a>
                        {% if user.is_staff %}
                            <a class="dropdown-item" href="{% url 'admin:index' %}"><i class="bi bi-gear-fill"></i> {% trans "Administration" %}</a>
                        {% endif %}
                        {% if "_fake_user_id" in request.session %}
                            <a class="dropdown-item" href="{% url "member:reset_impersonate" %}?path={{ request.path }}">
                                <i class="bi bi-gear-fill"></i> {% trans "Return to admin view" %}
                            </a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'logout' %}"><i class="bi bi-box-arrow-left"></i> {% trans "Logout" %}</a>
                    </div>
                </li>
                {% else %}
                    {% url 'member:signup' as signup_url %}
                    {% if request.path != signup_url %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ signup_url }}"><i class="bi bi-person-plus"></i> {% trans "Signup" %}</a>
                        </li>
                    {% endif %}
                    {% url 'login' as login_url %}
                    {% if request.path != login_url %}
                        <li class="nav-item">
                            <a class="nav-link" href="{{ login_url }}"><i class="bi bi-box-arrow-in-right"></i> {% trans "Login" %}</a>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<main class="mb-auto flex-shrink-0">
    {% if user.is_authenticated and not user.profile.email_confirmed %}
        <div class="alert alert-warning">
            {% url 'member:email_validation_resend' pk=user_object.pk as send_mail_url %}
            {% blocktrans trimmed %}
            Votre adresse électronique n'a pas été confirmée. Merci de cliquer sur le lien que vous avez reçu par mail.
            Si vous ne l'avez pas reçu, <a class="alert-link" href="{{ send_mail_url }}">vous pouvez en redemander un</a>.
            {% endblocktrans %}
        </div>
    {% endif %}

    {% include "messages.html" %}

    <div class="container my-3">
        {% block content %}Default content...{% endblock %}
    </div>
</main>

<footer class="bg-dark text-white py-2 mt-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1">
                <a class="text-muted" href="mailto:contact@crans.org">{% trans "Contact us" %}</a>
            </div>
            <div class="col-sm-10">
                <form action="{% url 'set_language' %}" method="post" class="form-inline">
                    {% csrf_token %}
                    <select title="language" name="language"
                            class="form-control form-control-sm language"
                            onchange="this.form.submit()">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% for lang_code, lang_name in LANGUAGES %}
                            <option value="{{ lang_code }}"
                                    {% if lang_code == LANGUAGE_CODE %}
                                    selected{% endif %}>
                                {{ lang_name }} ({{ lang_code }})
                            </option>
                        {% endfor %}
                    </select>
                    <noscript>
                        <input type="submit">
                    </noscript>
                </form>
            </div>
            <div class="col-sm-1 ms-auto">
                <a href="#" class="text-muted">
                    <i class="bi bi-arrow-up" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div>
</footer>

{% block extrajavascript %}{% endblock %}
</body>
</html>

constellation/templates/index.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
    <h1>{% trans "Welcome to Constellation!" %}</h1>

    <div>
        <p>
        {% blocktrans trimmed %}
            Constellation is a platform developed by the Crans to manage your membership, your Internet connection,
            your invoices and your connected machines.
        {% endblocktrans %}
        </p>

        <p>
        {% blocktrans trimmed %}
            If you don't have any account, you can create one by clicking on the top-right button. If you have one,
            you can log in to manage your account.
        {% endblocktrans %}
        </p>

        <p>
        {% blocktrans trimmed %}
            If you want to buy an Internet connection, you need to be a member of the Crans organization. This costs
            10€ for a year. After that, you will be able to pay for a connection, for 5€ per month.
        {% endblocktrans %}
        </p>

        <p>
        {% blocktrans trimmed %}
            When you join the Crans organization, you get access to multiple services, like a lifetime mailbox,
            a hosting of personal pages, 30 GB of storage, and a lot of other services.
            More information on <a href="https://www.crans.org/en/">https://www.crans.org/</a>.
        {% endblocktrans %}
        </p>

        <p>
        {% blocktrans trimmed %}
            If you have troubles with your Internet connection, please visit
            <a href="https://www.crans.org/en/connection/">https://www.crans.org/en/connection/</a>.
             If this does not help you, you can send an email to <a href="mailto:contact@crans.org">contact@crans.org</a>.
        {% endblocktrans %}
        </p>
    </div>

    {% if user.is_authenticated %}
        <a class="btn btn-success" href="{% url 'member:user_detail' pk=user.pk %}">
            <i class="bi bi-person-fill"></i> {% trans "Manage my account" %}
        </a>
    {% else %}
        <a class="btn btn-success" href="{% url 'member:signup' %}">
            <i class="bi bi-person-plus-fill"></i> {% trans "Register" %}
        </a>
        <a class="btn btn-secondary" href="{% url 'login' %}">
            <i class="bi bi-box-arrow-in-right"></i> {% trans "Log in" %}
        </a>
    {% endif %}
{% endblock %}

constellation/templates/messages.html
{% if messages %}
    <div id="messages">
        {% for message in messages %}
        <div class="container my-3">
          <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            {{ message }}
          </div>
        </div>
        {% endfor %}
    </div>
{% endif %}