billing/urls.py
from django.urls import path

from . import views


app_name = "billing"
urlpatterns = [
    path("purchase/<int:pk>/", views.PurchaseView.as_view(), name='purchase'),
    path("invoice_list/<int:pk>/", views.InvoiceListView.as_view(), name='invoice_list'),
    path('render-invoice/<int:pk>/', views.RenderInvoiceView.as_view(), name='render_invoice'),
    path('comnpay/redirect/<int:pk>/', views.RedirectComnpayView.as_view(), name='comnpay_redirect'),
    path('comnpay/ipn/', views.IPNComnpayView.as_view(), name='comnpay_ipn'),
    path('comnpay/success/', views.ComnpaySuccessView.as_view(), name='comnpay_success'),
    path('comnpay/fail/', views.ComnpayFailView.as_view(), name='comnpay_fail'),
]

constellation/urls.py
import importlib

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('admin/doc/', include('django.contrib.admindocs.urls'), name='admindocs'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('i18n/', include('django.conf.urls.i18n')),
]

# Load urls from other apps if they are loaded
for app in settings.INSTALLED_APPS:
    if app.startswith("django"):
        continue
    try:
        urlpatterns.append(path(f'{app}/', include(app + '.urls')))
    except ModuleNotFoundError:
        pass


# If Django Rest Framework is installed, then add a REST API
try:
    from rest_framework import routers
except ImportError:
    pass
else:
    router = routers.DefaultRouter()

    for app in settings.LOCAL_APPS:
        try:
            api_urls = importlib.import_module(f'{app}.api.urls')
            # noinspection PyUnresolvedReferences
            api_urls.register_routes(router)
        except ModuleNotFoundError:
            pass

    if 'dnsmanager' in settings.INSTALLED_APPS:
        from dnsmanager.api.views import RecordViewSet, ZoneViewSet
        router.register('dnsmanager/record', RecordViewSet)
        router.register('dnsmanager/zone', ZoneViewSet)

    urlpatterns += [
        url(r'^api/', include(router.urls)),
    ]

debug/urls.py
from django.urls import path

from . import views


app_name = 'debug'
urlpatterns = [
    path('graph/', views.GraphModelsView.as_view(), name='graph_models'),
]

member/api/urls.py
from rest_framework.routers import BaseRouter

from . import views


def register_routes(router: BaseRouter) -> None:
    router.register('auth/user', views.UserViewSet)
    router.register('member/membership', views.MembershipViewSet)

member/urls.py
from django.contrib import admin
from django.contrib.admin.views.autocomplete import AutocompleteJsonView
from django.urls import path

from . import views

app_name = 'member'
urlpatterns = [
    path("signup/", views.SignupView.as_view(), name='signup'),
    path("detail/<int:pk>/", views.UserDetailView.as_view(), name='user_detail'),
    path("update/<int:pk>/", views.UserUpdateView.as_view(), name='user_update'),
    path('validate_email/resend/<int:pk>/', views.UserResendValidationEmailView.as_view(),
         name='email_validation_resend'),
    path('validate_email/<uidb64>/<token>/', views.UserValidateView.as_view(), name='email_validation'),
    path("impersonate/<int:pk>/", views.UserImpersonateView.as_view(), name="user_impersonate"),
    path("reset-impersonate/", views.ResetAdminView.as_view(), name="reset_impersonate"),
    # Autocomplete view that don't require to be staff
    path("autocomplete/", AutocompleteJsonView.as_view(admin_site=admin.site), name="autocomplete"),
]

member/forms.py
from collections import namedtuple

from django import forms
from django.contrib.admin.widgets import AutocompleteSelectMultiple
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

from member.models import Person, Organization


class SignupForm(UserCreationForm):
    gtu = forms.BooleanField(
        label=_("I read and accept the general terms of use."),
        required=True,
    )

    no_double_account = forms.BooleanField(
        label=_("I certify that I don't have already an account."),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['username'].help_text = _("Required. 32 characters or fewer. Lowercase letters, "
                                              "digits and dashes only.")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'gtu', 'no_double_account',)


class UserForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['username'].help_text = _("Required. 32 characters or fewer. Lowercase letters, "
                                              "digits and dashes only.")

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email',)


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('address', 'telephone',)


class OrganizationForm(forms.ModelForm):

    class Meta:
        model = Organization
        fields = ('address', 'members',)
        widgets = {
            'members': AutocompleteSelectMultiple(
                field=Organization._meta.get_field('members'),
                admin_site=namedtuple('AdminSite', 'name')('member'),  # Use local autocomplete view
            ),
        }

member/api/views.py
from django.contrib.auth.models import User
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter

from .serializers import MembershipSerializer, UserSerializer
from ..models import Membership


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer
    filter_backends = (DjangoFilterBackend,)
    filterset_fields = ('username', 'last_name', 'first_name', 'email', 'profile__address',
                        'profile__member__telephone', 'profile__member__pgp',
                        'profile__organization__manager__user__username',
                        'profile__organization__manager__user__last_name',
                        'profile__organization__manager__user__first_name',
                        'profile__organization__manager__user__email',
                        'profile__organization__manager__address',
                        'profile__organization__manager__telephone',
                        'profile__polymorphic_ctype',)
    lookup_field = 'username'


class MembershipViewSet(viewsets.ModelViewSet):
    queryset = Membership.objects.all()
    serializer_class = MembershipSerializer
    filter_backends = (DjangoFilterBackend, OrderingFilter,)
    filterset_fields = ('date_start', 'date_end', 'member__user__username', 'member__user__last_name',
                        'member__user__first_name', 'member__user__email',)
    ordering_fields = ('date_start', 'date_end',)

member/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import transaction
from django.http import Http404
from django.shortcuts import redirect, resolve_url
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.http import urlsafe_base64_decode
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, DetailView, UpdateView, RedirectView, TemplateView

from . import forms
from .models import Person
from .tokens import email_validation_token


@method_decorator(sensitive_post_parameters('password1', 'password2'), 'dispatch')
class SignupView(CreateView):
    model = User
    form_class = forms.SignupForm
    template_name = 'member/signup.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['member_form'] = forms.PersonForm(self.request.POST or None)
        return context

    @transaction.atomic
    def form_valid(self, form):
        member_form = forms.PersonForm(self.request.POST or None)
        if not member_form.is_valid():
            return self.form_invalid(form)

        ret = super().form_valid(form)

        member = member_form.instance
        member.user = form.instance
        member.save()

        return ret

    def get_success_url(self):
        return reverse_lazy('member:user_detail', args=(self.object.pk,))


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    context_object_name = 'user_object'
    template_name = 'member/user_detail.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = forms.UserForm
    context_object_name = 'user_object'
    template_name = 'member/user_update.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        profile_form_class = forms.PersonForm if isinstance(user.profile, Person) else forms.OrganizationForm
        context['profile_form'] = profile_form_class(data=self.request.POST or None, instance=user.profile)
        return context

    @transaction.atomic
    def form_valid(self, form):
        user = form.instance
        profile_form_class = forms.PersonForm if isinstance(user.profile, Person) else forms.OrganizationForm
        profile_form = profile_form_class(data=self.request.POST or None, instance=user.profile)
        if not profile_form.is_valid():
            return self.form_invalid(form)

        ret = super().form_valid(form)

        profile_form.save()

        return ret

    def get_success_url(self):
        return reverse_lazy('member:user_detail', args=(self.object.pk,))


class UserValidateView(TemplateView):
    """
    A view to validate the email address.
    """
    template_name = 'member/email_validation_complete.html'

    def get(self, *args, **kwargs):
        """
        With a given token and user id (in params), validate the email address.
        """
        assert 'uidb64' in kwargs and 'token' in kwargs

        self.validlink = False
        user = self.get_user(kwargs['uidb64'])
        token = kwargs['token']

        # Validate the token
        if user is not None and email_validation_token.check_token(user, token):
            # The user must wait that someone validates the account before the user can be active and login.
            self.validlink = True
            user.profile.email_confirmed = True
            user.save()
            user.profile.save()
        return self.render_to_response(self.get_context_data(), status=200 if self.validlink else 400)

    def get_user(self, uidb64):
        """
        Get user from the base64-encoded string.
        """
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_object'] = self.get_user(self.kwargs["uidb64"])
        context['login_url'] = resolve_url(settings.LOGIN_URL)
        if self.validlink:
            context['validlink'] = True
        else:
            context.update({
                'title': _('Email validation unsuccessful'),
                'validlink': False,
            })
        return context


class UserResendValidationEmailView(LoginRequiredMixin, DetailView):
    """
    Resend the email validation link.
    """
    model = User

    def get(self, request, *args, **kwargs):
        user = self.get_object()

        if user != request.user and not request.user.has_perm('member.change_profile'):
            raise Http404

        user.profile.send_email_validation_link()
        messages.info(request, _("Email confirmation link was successfully sent"))

        return redirect('member:user_detail', user.id)


class UserImpersonateView(LoginRequiredMixin, RedirectView):
    """
    An administrator can log in through this page as someone else,
    and act as this other person.
    """

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_superuser:
            if not User.objects.filter(pk=kwargs["pk"]).exists():
                raise Http404
            session = request.session
            session["admin"] = request.user.pk
            session["_fake_user_id"] = kwargs["pk"]
        return super().dispatch(request, *args, **kwargs)

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy("member:user_detail", args=(kwargs["pk"],))


class ResetAdminView(LoginRequiredMixin, View):
    """
    Return to admin view, clear the session field
    that let an administrator to log in as someone else.
    """

    def dispatch(self, request, *args, **kwargs):
        user = request.user
        if not user.is_authenticated:
            return self.handle_no_permission()
        if "_fake_user_id" in request.session:
            del request.session["_fake_user_id"]
        return redirect(request.GET.get("path", reverse_lazy("index")))

member/templates/member/email_validation_complete.html
{% extends "base.html" %}
{% comment %}
SPDX-License-Identifier: GPL-3.0-or-later
{% endcomment %}
{% load i18n %}

{% block content %}
<div class="card bg-light">
    <h3 class="card-header text-center">
        {% trans "Validate email address" %}
    </h3>
    <div class="card-body">
        {% if validlink %}
        <p>
            {% trans "Your email have successfully been validated." %}
        </p>
        <p>
            {% blocktrans %}You can now <a href="{{ login_url }}">log in</a>.{% endblocktrans %}
        </p>
        {% else %}
        <p>
            {% trans "The link was invalid. The token may have expired. Please send us an email to activate your account." %}
        </p>
        {% endif %}
     </div>
</div>
{% endblock %}

member/templates/member/signup.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% load i18n %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {{ member_form|crispy }}
        <button class="btn btn-success" type="submit">{% trans "Register" %}</button>
    </form>
{% endblock %}

member/templates/member/user_detail.html
{% extends "base.html" %}

{% load apps i18n %}

{% block content %}
    <div class="card">
    <div class="card-header text-center">
        <h1>{{ user_object.get_full_name }}</h1>
    </div>
    <div class="card-body">
        <dl class="row col-sm-12">
            <dt class="col-sm-6">{% trans "last name"|capfirst %} :</dt>
            <dd class="col-sm-6">{{ user_object.last_name }}</dd>

            {% if user_object.profile.is_person %}
                <dt class="col-sm-6">{% trans "first name"|capfirst %} :</dt>
                <dd class="col-sm-6">{{ user_object.first_name }}</dd>
            {% endif %}

            <dt class="col-sm-6">{% trans "username"|capfirst %} :</dt>
            <dd class="col-sm-6">{{ user_object.username }}</dd>

            <dt class="col-sm-6">{% trans "password"|capfirst %} :</dt>
            <dd class="col-sm-6"><a class="btn btn-secondary" href="{% url 'password_change' %}"><i class="bi bi-pencil"></i> {% trans "Change password" %}</a></dd>

            <dt class="col-sm-6">{% trans "email address"|capfirst %} :</dt>
            <dd class="col-sm-6"><a href="mailto:{{ user_object.email }}">{{ user_object.email }}</a></dd>

            <dt class="col-sm-6">{% trans "address"|capfirst %} :</dt>
            <dd class="col-sm-6">{{ user_object.profile.address }}</dd>

            {% if user_object.profile.member %}
                <dt class="col-sm-6">{% trans "telephone"|capfirst %} :</dt>
                <dd class="col-sm-6"><a href="tel:{{ user_object.profile.telephone }}">{{ user_object.profile.telephone }}</a></dd>

                {% if user_object.profile.pgp %}
                    <dt class="col-sm-6">{% trans "PGP fingerprint"|capfirst %} :</dt>
                    <dd class="col-sm-6">{{ user_object.pgp }}</dd>
                {% endif %}
            {% else %}
                <dt class="col-sm-6">{% trans "manager"|capfirst %} :</dt>
                <dd class="col-sm-6">{{ user_object.profile.manager }}</dd>

                <dt class="col-sm-6">{% trans "members"|capfirst %} :</dt>
                <dd class="col-sm-6">{{ user_object.profile.members.all|join:", " }}</dd>
            {% endif %}
            {% if not user_object.profile.has_current_membership %}
                <dt class="col-sm-6">{% trans "valid membership"|capfirst %} :</dt>
                <dd class="col-sm-6">
                    {{ user_object.profile.current_membership }}
                    {% if user_object.profile.is_organization %}
                        {% trans "(issued from its manager)" %}
                    {% endif %}
                </dd>
            {% else %}
                <dt class="col-sm-6">{% trans "not yet a member"|capfirst %} :</dt>
                {% if 'billing'|app_loaded and user_object.profile.is_member %}
                    <dd class="col-sm-6">
                    <a class="btn btn-primary" href="{% url 'billing:purchase' pk=user_object.pk %}">
                        <i class="bi bi-cart4"></i> {% trans "Purchase a membership now" %}
                    </a>
                {% elif user_object.profile.is_organization %}
                    <dd class="col-sm-6">
                        <div class="btn btn-warning">
                        {% trans "The manager of the organization should adhere" %}
                        </div>
                    </dd>
                {% endif %}
            {% endif %}
        </dl>
    </div>
    <div class="card-footer text-center">
        <a class="btn btn-primary" href="{% url 'member:user_update' pk=user_object.pk %}">
            <i class="bi bi-pencil-fill"></i> {% trans "Update" %}
        </a>
        {% if 'billing'|app_loaded %}
            <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#invoicesModal">
                <i class="bi bi-file-earmark-text"></i> {% trans "All invoices" %}
            </button>
        {% endif %}
    </div>

    {% if 'billing'|app_loaded %}
        <div class="card-footer text-center">
            <a class="btn btn-tiny btn-success" href="{% url 'billing:purchase' pk=user_object.pk %}">
                <i class="bi bi-cart4"></i> {% trans "Purchase a membership/connection/product..." %}
            </a>
        </div>
    {% endif %}

    {% if request.user.is_superuser %}
        <div class="card-footer text-center">
            <a class="btn btn-info" href="{% url 'member:user_impersonate' pk=user_object.pk %}">
                <i class="bi bi-bug-fill"></i> {% trans "impersonate"|capfirst %}
            </a>
            <a class="btn btn-danger" href="{% url 'admin:auth_user_change' user_object.pk %}">
                <i class="bi bi-gear-fill"></i> {% trans "access to admin interface"|capfirst %}
            </a>
        </div>
    {% endif %}
    </div>

    {% if 'billing'|app_loaded %}
    <div class="modal fade" id="invoicesModal" tabindex="-1" aria-labelledby="invoices" aria-hidden="true">
      <div class="modal-dialog modal-xl">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
                <a href="{% url 'billing:invoice_list' pk=user_object.pk %}">
                    {% trans "All invoices" %}
                </a>
            </h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="invoicesModalBody">
              {% trans "Loading..." %}
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans "Close" %}</button>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
{% endblock %}

{% block extrajavascript %}
    <script>
        {% if 'billing'|app_loaded %}
            modal = document.getElementById('invoicesModal')
            body = document.getElementById('invoicesModalBody')

            modal.addEventListener('shown.bs.modal', function() {
                fetch("{% url 'billing:invoice_list' pk=user_object.pk %}").then(res => {
                    res.text().then(text => {
                        body.innerHTML = new DOMParser().parseFromString(text, 'text/html').getElementById('table').innerHTML
                    })
                })
            })
        {% endif %}
    </script>
{% endblock %}

member/templates/member/user_update.html
{% extends "base.html" %}

{% load crispy_forms_filters %}
{% load i18n %}
{% load static %}

{% block form_media %}
    {{ block.super }}
    {{ profile_form.media }}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        {{ profile_form|crispy }}
        <button class="btn btn-primary" type="submit">{% trans "Update" %}</button>
    </form>
{% endblock %}